services:
  - type: web
    name: consultorio
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn consultorio_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0